### PR TITLE
Fix fonts rute

### PR DESCRIPTION
**Pull request by JesusChapman**
Hi friend, there is a small error, the fonts do not save in .termux, they are saved is in .fonts, so your program did not show me the icons

### CODE REVIEW

**Comment by laraib07** [comment]
Hello, the font in termux is stored in `~/.termux/font.ttf`.
source : https://wiki.termux.com/wiki/Termux:Styling

I checked if moving it to `~/.fonts` will work or not. It didn't worked.

**Comment by JesusChapman** [comment]
Well, when I installed it it didn't work, and after having moved the photos to .fonts it worked correctly, that's why I do that edit

**Comment by JesusChapman** [comment]
Besides, there are 2 types of fonts, the ones that are for termux is saved in .termux, the ones that are to program like yours should be saved in any of these paths :  

```
~/.fonts
~/.local/share/fonts
$PREFIX/share/fonts
```

**Comment by laraib07** [comment]
> Besides, there are 2 types of fonts, the ones that are for termux is saved in .termux, the ones that are to program like yours should be saved in any of these paths :
> 
> ```
> ~/.fonts
> ~/.local/share/fonts
> $PREFIX/share/fonts
> ```

I don't think things work in termux this way.

FWIW, after installing any font on termux you must start a new session or run command `termux-reload-settings` to see any changes.

**Comment by JesusChapman** [comment]
Well, I got a mistake in your own way, but thank you the same.

**Pull request closed without merging**
